### PR TITLE
Add slash command /condalock to autogenerate conda-lock files

### PR DESCRIPTION
**Pull request by weiji14**
To enable easier reproducibility of conda environments, create an automated way of refreshing [conda-lock](https://github.com/conda-incubator/conda-lock) files by writing `/condalock` as as slash command in Pull Request comments.

Related to https://github.com/CryoInTheCloud/CryoCloudWebsite/issues/1#issuecomment-1326641419

Based on:
- https://github.com/GenericMappingTools/pygmt/pull/646
- https://github.com/pangeo-data/pangeo-docker-images/pull/33

TODO setup auth tokens for automated commits, based on https://github.com/GenericMappingTools/pygmt/pull/646#discussion_r511169428
- [x] Create a `CryoInTheCloud` GitHub App to generate tokens, following
  - https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
  - https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app
- [x] Install `cryointhecloud-bot` in this repository
- [x] Add `APP_ID` and `APP_PRIVATE_KEY` as secrets to the repo
- [x] Test to see if conda-lock files are generated! (https://github.com/weiji14/hub-image/pull/3)

### CODE REVIEW

**Comment by weiji14** [comment]
@yuvipanda, I've just created a `cryointhecloud-bot` GitHub App and have sent a request to transfer it to the CryoInTheCloud GitHub org. That GitHub App will be used to make git commits when conda-lock files are refreshed, similar to https://github.com/pangeo-bot (but the GitHub App isn't a user account, just a machine user). If you can approve that request, that would be great :pray:

After that, we'll need to set the `APP_ID` and `APP_PRIVATE_KEY` secrets in this repo. See if you can add those in based on the GitHub App, or if someone can grant me access, I can add them in too.

**Comment by yuvipanda** [comment]
@weiji14 you should have access now!

**Comment by weiji14** [comment]
Cool, thanks Yuvi! Let me do some testing to see if it works.

**Comment by weiji14** [comment]
Yay, it works! Tested this on a personal fork (since the workflow needs to be tested on the main branch).

So I wrote the `/condalock` command at https://github.com/weiji14/hub-image/pull/3#issuecomment-1327932003, which kicked off a GitHub Actions workflow at https://github.com/weiji14/hub-image/actions/runs/3551298148/jobs/5965359133#step:6:14, and the bot successfully updated the conda-lock files at https://github.com/weiji14/hub-image/pull/3/commits/e16f6b6cc7bc196c5700658e58b689c31ec86b39!

**Comment by weiji14** [comment]
Sure! Right now this is only generating the ['old' explicit lockfile](https://github.com/conda-incubator/conda-lock/tree/v1.2.1#pre-10-compatible-usage-explicit-per-platform-locks) from `conda-lock<1.0` (`conda-linux-64.lock`) instead of the [newer unified lockfile](https://conda-incubator.github.io/conda-lock/output/#unified-lockfile) (`conda-lock.yml`). The old explicit lockfile is compatible with `conda`/`mamba` and repo2docker but doesn't include the pip dependencies, whereas the newer unified lockfile contains both conda/pip dependencies but can't be used by repo2docker (yet). Just noting this for future reference.

**Pull request merged**
