### PR TITLE
Add awscli and h5coro

### LINKED ISSUE #79: requesting aws cli and H5Coro
We are at the IS2 Hackweek working with HDF5 data and it will be nice if the base image had

* awscli v2 (either the official binary or the community maintained https://anaconda.org/conda-forge/awscliv2)
* [H5Coro](https://anaconda.org/conda-forge/h5coro)

### PR DESCRIPTION
**Pull request by weiji14**
Adding two packages requested for ICESat-2 Hackweek 2023
- awscli https://anaconda.org/conda-forge/awscli
- h5coro https://anaconda.org/conda-forge/h5coro

Also updating `s3fs` to 2023.6.0, to make it compatible with `awscli==1.27.76` which requires `botocore >=1.29.76,<1.29.77`

Closes #79

### CODE REVIEW

**Review by tsnow03 — APPROVED** [review]

**Comment by tsnow03** [comment]
In our Slack channel, we noted potential conflicts between awscli and boto3. We also noted a change to s3fs, but that should not change any of our existing code. We will need to roll back awscli if any big conflicts come up, but otherwise should be good.

**Comment by weiji14** [comment]
Yes, I've handled the conflict with awscli and boto3 already at 2cadcf734d14c82c06da8285269637bcf874f5ae, and the docker image build from the resulting lockfile at c958ab7d76cd878dfd1e3059e57b91f5055cffab has succeeded, so should be ok.

**Pull request merged**
