### PR TITLE
bump jupyterlab-myst -> 2

### PR DESCRIPTION
**Pull request by scottyhq**
https://github.com/executablebooks/jupyterlab-myst/releases

I think this would be nice to render 'exercises' & 'solutions' in tutorials notebooks. We added this recently to the Xarray tutorial, you can see an example here: https://tutorial.xarray.dev/intermediate/xarray_and_dask.html#getting-concrete-values

Also is compatible with jupyterlab4 if that is desirable down the line

### CODE REVIEW

**Comment by weiji14** [comment]
Hmm, conda-lock seems to have timed out. Might need to try locking locally to see if there are other dependencies that need to be upgraded too.

**Comment by weiji14** [comment]
So I tried running `conda-lock lock --mamba --kind explicit --file environment.yml --platform linux-64` locally and got this:

```bash
Locking dependencies for ['linux-64']...
INFO:conda_lock.conda_solver:linux-64 using specs ['python ~=3.10.10', 'jupyterhub-singleuser >=3.0,<4.0', 'nbgitpuller 1.1.1', 'jupyterlab >=3.0,<4.0', 'jupyter-resource-usage 0.7.1', 'jupyter-syncthing-proxy 1.0.3', 'syncthing 1.22.1', 'gh-scoped-creds 4.1', 'ipython 8.6.0', 'ipykernel 6.16.0.*', 'ipywidgets 7.7.2', 'jupyterlab-favorites 3.1.0', 'jupyterlab-geojson 3.3.1', 'jupyterlab-git 0.41.0', 'jupyterlab-myst ~=2.0.1', 'jupyter-book 0.13.2', 'jupytext 1.14.1', 'nbconvert 6.5.3', 'nbdime 3.1.1', 'cython 0.29.32', 'hypothesis 6.58.0', 'networkx 2.8.8', 'numba 0.56.4', 'numpy 1.23.5', 'pandas 1.5.2', 'scikit-image 0.19.3', 'scikit-learn 1.1.3', 'scipy 1.9.3', 'statsmodels 0.13.5', 'sympy 1.11.1', 'xarray >=2023.05.0', 'bokeh 2.4.3', 'cartopy ~=0.21.1', 'geoviews 1.9.5', 'hvplot 0.8.2', 'ipyleaflet ~=0.17.3', 'ipympl 0.9.2', 'matplotlib 3.6.2', 'plotly 5.11.0', 'seaborn 0.12.1', 'geopandas 0.12.1', 'rasterio ~=1.3', 'rioxarray ~=0.14.1', 'xarray-datatree ~=0.0.12', 'h5py ~=3.8', 'hdf5 ~=1.14', 'h5netcdf 1.1.0', 'pooch 1.6.0', 'boto3', 's3fs 2022.11.0', 'earthaccess 0.5.1', 'pystac-client 0.5.1', 'intake 0.6.6', 'intake-esm 2022.9.18', 'intake-stac 0.4.0', 'intake-xarray 0.6.1', 'dask 2022.11.0', 'dask-labextension 6.0.0', 'dask-geopandas ~=0.3.1', 'pillow ~=9.5', 'pytest 7.2.0', 'pytest-cov 4.0.0', 'pep8 1.7.1', 'flake8 5.0.4', 'tqdm 4.64.1', 'icepyx 0.7.0', 'sliderule ~=3.5.0', 'qgis ~=3.28.6', 'pyopencl', 'ocl-icd-system', 'websockify >=0.10', 'git >=2.39', 'pip *']
Failed to parse json, Expecting value: line 1 column 1 (char 0)
Could not lock the environment for platform linux-64
Could not solve for environment specs
The following packages are incompatible
├─ jupyterlab-myst ~=2.0.1  is installable and it requires
│  └─ jupyterlab >=4,<5 , which can be installed;
└─ jupyterlab >=3.0,<4.0  is not installable because it conflicts with any installable versions previously reported.
```
Seems like `jupyterlab-myst=2.0.1` requires jupyterlab 4? Should we update jupyterlab then, or would the other jupyterlab extensions be a problem as they don't support jupyterlab 4 yet?

**Comment by scottyhq** [comment]
> Seems like jupyterlab-myst=2.0.1 requires jupyterlab 4? Should we update jupyterlab then, or would the other jupyterlab extensions be a problem as they don't support jupyterlab 4 yet? 

Thanks for trying. I didn't realize jupyterlab 4 was required. This can wait if other extensions aren't compatible

**Comment by tsnow03** [comment]
I would love to have this available for the hackweek, but testing with JupyterLab 4 may be a bear so I think we will want to wait until after the hackweek.

**Comment by scottyhq** [comment]
> would the other jupyterlab extensions be a problem as they don't support jupyterlab 4 yet?

curious if this could now be revisited, or if not, which extensions do no support jlab4

**Pull request closed without merging**
