### PR TITLE
Bump to cartopy 0.21.0, rasterio 1.3.3, hdf5 1.12.2, qgis 3.22.11

### PR DESCRIPTION
**Pull request by weiji14**
Minor version updates to fix `mamba` solver as reported in https://github.com/CryoInTheCloud/hub-image/pull/13#issuecomment-1330840738. Cherry-picked from #14.

### CODE REVIEW

**Comment by yuvipanda** [comment]
It looks like merge commits are disabled for this repository, do you know why? I think they're extremely helpful in figuring out which PR a particular change landed in...

**Comment by yuvipanda** [comment]
I've just re-enabled them, but not sure why they were disabled in the first place...

**Comment by weiji14** [comment]
Ah sorry, I usually go with squash and merge to keep a linear history. Ok with re-enabling them too if you prefer it that way.

**Comment by yuvipanda** [comment]
@weiji14 yeah, I really like not losing individual commit messages! I think we can rebase and merge too if you prefer.

**Comment by weiji14** [comment]
Let's stick with regular merges. There shouldn't be too many people making changes to this repo so I can live with a bit of spaghetti git history.

**Pull request merged**
