### PR TITLE
Add PyGMT

### PR DESCRIPTION
**Pull request by weiji14**
A Python interface for the Generic Mapping Tools. Repo at https://github.com/GenericMappingTools/pygmt

Partially addresses #86.

### CODE REVIEW

**Comment by weiji14** [comment]
Getting this error message in the test build at https://github.com/CryoInTheCloud/hub-image/actions/runs/6243963744/job/16950178339#step:5:3426:

```bash
  E: Unable to locate package python-mode
  Removing intermediate container 730766d7cba1
  The command '/bin/sh -c apt-get -qq update && apt-get install --yes --no-install-recommends ack build-essential chromium-browser curl dbus-x11 emacs emacs-goodies-el emacs-nox firefox gedit gfortran git-gui gitg htop imagemagick jed jed-extra latexdiff latexmk libgl1-mesa-glx lmodern man man-db manpages-dev manpages-posix manpages-posix-dev mc meld mr multitail nano nnn pandoc perl-doc pydf python-mode qgit rsync ruby screen texlive-fonts-extra texlive-fonts-recommended texlive-lang-chinese texlive-plain-generic texlive-science texlive-xetex tig tmux tree vim vim-gtk3 wget xclip xfce4 xfce4-goodies xorg xsel xubuntu-icon-theme zsh && apt-get -qq purge && apt-get -qq clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

From what I can tell, the default docker base image used by repo2docker has changed (see https://github.com/jupyterhub/repo2docker/pull/1287) from `docker.io/library/buildpack-deps:bionic` (18.04) to `docker.io/library/buildpack-deps:jammy` (22.04), so we'll need to update some packages in `apt.txt` that are not available in Ubuntu 22.04 Jammy Jellyfish.

**Review by MattF-NSIDC — APPROVED** [review]
:rocket:

**Pull request merged**
