### PR TITLE
Add nco

### LINKED ISSUE #83: Install nco on jupyterhub?
Would it be possible to install nco (https://nco.sourceforge.net/) on the jupyterhub?

Thanks!
David

### PR DESCRIPTION
**Pull request by weiji14**
Suite of programs for manipulating NetCDF/HDF4 files. Repo at https://github.com/nco/nco

Closes #83.

### CODE REVIEW

**Review by MattF-NSIDC — APPROVED** [review]
LGTM!

**Comment by davidclemenssewall** [comment]
Hi!

Sorry to open this again, but in my jupyterhub I don't seem to have access to nco. For example in the terminal:
```
notebook) jovyan@jupyter-davidclemenssewall:~/code/IS2BS/data$ ncra

Command 'ncra' not found, but can be installed with:

apt install nco
Please ask your administrator.
```
Is there something I need to do to update my jupyterhub? Sorry if this is obvious. I did try stopping and restarting my server at least...

Thanks!
David

**Comment by MattF-NSIDC** [comment]
@tsnow03 has this change been released into CryoCloud yet?

**Pull request merged**
