### PR TITLE
Add desktop shortcuts to qgis

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by weiji14** [comment]
Need to add the `start` file to https://github.com/CryoInTheCloud/hub-image/blob/26eb812a9999525f8fd2d3ded5d0170f52a50ab5/.github/workflows/build.yaml#L7-L10 and https://github.com/CryoInTheCloud/hub-image/blob/26eb812a9999525f8fd2d3ded5d0170f52a50ab5/.github/workflows/test.yaml#L5-L8 so that the docker build is triggered.

In fact, I should probably have added all of the config files listed under https://repo2docker.readthedocs.io/en/latest/config_files.html#configuration-files while doing #10...

**Comment by weiji14** [comment]
So QGIS 3.22 couldn't be installed at bbd75cca43c65029622a0ff90b21d79147d526b5 because of cartopy pinned to 0.20.2, see https://github.com/CryoInTheCloud/hub-image/actions/runs/3571789674/jobs/6003992007#step:5:4030.

```
- package cartopy-0.20.2-py310h902574e_0 requires geos >=3.10.1,<3.10.2.0a0, but none of the providers can be installed
```

Tried to use the newer `cartopy=0.21.0` locally, and then it gave this error:

```
package qgis-3.22.11-py310heaafcf0_0 requires pdal >=2.4.3,<2.5.0a0, but none of the providers can be installed
```

So need to wait for things to sort out in PDAL, I think at https://github.com/conda-forge/pdal-feedstock/pull/190.

**Comment by yuvipanda** [comment]
@weiji14 do you know why this might still be failing? I have removed all changes to qgis

**Comment by weiji14** [comment]
> @weiji14 do you know why this might still be failing? I have removed all changes to qgis

I'm slowly working through the dependency pins. Something with the recent GDAL mayhem. Give me an hour or so...

**Comment by weiji14** [comment]
Ok, I think I've found a good combination that works with the `mamba` solver. Need to bump up versions of `cartopy`, `rasterio`, `hdf5` and `qgis`. See https://github.com/CryoInTheCloud/hub-image/pull/14/commits/90fe9f603fbb3df66a5cb1a9663e7e6807d451f0.

**Comment by yuvipanda** [comment]
@weiji14 perfect! So I'll just wait for that PR to land and then rebase this one.

**Review by weiji14 — APPROVED** [review]
Ok, tests passing now, feel free to merge as you please Yuvi!

Oh, and we should probably start tagging the images, especially those that are deployed to the CryoCloud hub.

**Comment by yuvipanda** [comment]
Thanks @weiji14! And yes re: tagging. Not sure how to automate that...

**Comment by weiji14** [comment]
Hmm, there was some tagging stuff in the CryoCloudWebsite repo we could copy over I think? I do feel like we're slowly moving in the direction of https://github.com/pangeo-data/pangeo-docker-images 😂

**Comment by yuvipanda** [comment]
@weiji14 how do you feel about extracting the conda-lock stuff from here into an action by itself? Then we can use *that* action in pangeo-docker-images, thus removing duplicate work...

**Pull request merged**
