### PR TITLE
Pin sphinx to 7.3, bump awscli to 2.17, downgrade ipython to 8.17

### PR DESCRIPTION
**Pull request by weiji14**
Syncing with the changes at https://github.com/ICESAT-2HackWeek/website-2024/pull/18 by:

- Pinning `sphinx` explicity to 7.3 (was resolving to 5.1.1 before)
- Upgrade `awscli` from 1.27.76 to 2.17 to resolve conflict on `docutils` (see https://github.com/ICESAT-2HackWeek/website-2024/pull/18#discussion_r1706350393)
- Downgrade `ipython` from 8.20.0 to 8.17 to resolve conflict on `prompt_toolkit` (see https://github.com/ICESAT-2HackWeek/website-2024/pull/18#discussion_r1706350990)

This PR also adds a 'conda-lock.yml' (following #122) in addition to the existing 'conda-lock-linux64.yml' file.

### CODE REVIEW

**Comment by weiji14** [comment]
@scottyhq, could you review (and approve) so that I can merge and work on adding some more packages for #118 later? Want to try to get some more dependencies in befor @tsnow03 pushes an update to the hub.

**Comment by tsnow03** [comment]
I requested they add the last image and we will get it changed again once this PR is incorporated next week.

**Review by scottyhq — APPROVED** [review]
Sorry I missed your request for review here @weiji14 . 

If you want to include it here, could also add stackstac (https://github.com/ICESAT-2HackWeek/website-2024/pull/22) 

Also, would be great to bump snowexsql once this is merged https://github.com/conda-forge/snowexsql-feedstock/pull/1

Can of course just do these separately though

**Pull request merged**
